#!/bin/bash

# Specify the path to your AWS credentials file
AWS_CREDENTIALS_FILE="credentials"
echo "Starting exporting credentials"

# Check if the credentials file exists
if [ ! -f "$AWS_CREDENTIALS_FILE" ]; then
  echo "AWS credentials file not found: $AWS_CREDENTIALS_FILE"
  exit 1
fi

# Extract the values from the credentials file
AWS_ACCESS_KEY_ID=$(grep -o 'aws_access_key_id = [^ ]*' "$AWS_CREDENTIALS_FILE" | awk '{print $3}')
AWS_SECRET_ACCESS_KEY=$(grep -o 'aws_secret_access_key = [^ ]*' "$AWS_CREDENTIALS_FILE" | awk '{print $3}')
AWS_SESSION_TOKEN=$(grep -o 'aws_session_token = [^ ]*' "$AWS_CREDENTIALS_FILE" | awk '{print $3}')

# Check if any of the required variables are empty
if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_SESSION_TOKEN" ]; then
  echo "One or more AWS credential values could not be extracted from the file."
  exit 1
fi

# Export the variables as environment variables
export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export AWS_SESSION_TOKEN

echo "AWS credentials exported:"
echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
echo "AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN"
